-- Align DB with Prisma schema used by FX / multi-currency features

ALTER TABLE "currencies" ADD COLUMN IF NOT EXISTS "lastSyncedAt" TIMESTAMP(3);

ALTER TABLE "sales" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'USD';
ALTER TABLE "sales" ADD COLUMN IF NOT EXISTS "exchangeRate" DECIMAL(18,8) NOT NULL DEFAULT 1;

ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'USD';
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "exchangeRate" DECIMAL(18,8) NOT NULL DEFAULT 1;
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "amountBase" DECIMAL(18,4) NOT NULL DEFAULT 0;

ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'USD';
ALTER TABLE "invoices" ADD COLUMN IF NOT EXISTS "exchangeRate" DECIMAL(18,8) NOT NULL DEFAULT 1;